In [1]:
import tensorflow as tf

D:\anaconda\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


让我们修改前面的代码去实现Mini-Batch梯度下降<br/>
为了去实现这个，我们需要一种方式去取代X和y在每一次迭代中，使用一小批数据<br/>
最简单的方式去做到这个是去使用placeholder节点<br/>
这些节点特点是它们不真正的计算，它们只是在执行过程中你要它们输出数据的时候去输出数据<br/>
它们会传输训练数据给TensorFlow在训练的时候<br/>
如果在运行过程中你不给它们指定数据，你会得到一个异常<br/>

In [3]:
A = tf.placeholder(dtype=tf.float32, shape=(None, 3))
B = A + 5

In [4]:
with tf.Session() as sess:
    B_val_1 = B.eval(feed_dict={A:[[1, 2, 3]]})
    B_val_2 = B.eval(feed_dict={A:[[1, 2, 3],
                                  [4, 5, 6]]})

In [5]:
print(B_val_1)
print(B_val_2)

[[6. 7. 8.]]
[[ 6.  7.  8.]
 [ 9. 10. 11.]]
